// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Carpe Diem",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Carpe Diem",
            targets: ["AppModule"],
            bundleIdentifier: "Giovanni.Carpe-Diem",
            teamIdentifier: "DVMDCJRNKS",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .location),
            accentColor: .presetColor(.yellow),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)